table Texte
	lineageTag: 07b59ffb-39cd-4386-b7ab-1bdee64723f4

	measure Date-titre =
			
			VAR __date = CALCULATE(MAX(Texte[Texte]),Texte[Titre]="Date")
			VAR __date_format_date = max(Texte[Date])
			VAr __decompte=DATEDIFF(DATE(2022,2,24),__date_format_date,DAY)+1
			RETURN COMBINEVALUES(" ",__date, "- jour", __decompte)
		lineageTag: 1185f4a3-2e55-4fa2-8163-9a52f0f3f651

	column Titre
		dataType: string
		lineageTag: cd088b89-a463-49f1-8e3b-2b57c99372be
		summarizeBy: none
		sourceColumn: Titre
		sortByColumn: Ordre

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Titre_dyn = if(Texte[Catégorie]=Texte[Titre],BLANK(),Texte[Titre])
		lineageTag: 11f0fe19-54d7-44a5-932d-8075e77ac404
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: d mmmm yyyy
		lineageTag: 752993e5-1df5-4f77-a175-19bb5883251e
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: e3c18fdf-b424-4949-aec0-ef547b3ba2eb
			defaultHierarchy: LocalDateTable_b457552e-890f-4edd-a13a-24fa9d560fa6.'Hiérarchie de dates'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Titre_display = CONCATENATE("➤ ", Texte[Titre])
		lineageTag: c0063245-dda1-4158-8fc4-3c0c77e20ba7
		summarizeBy: none
		sortByColumn: Ordre

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Texte display' = COMBINEVALUES(" : ",Texte[Titre_display],Texte[Texte])
		lineageTag: fb288aae-a937-4223-8d59-a2b7b2deb233
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column test = FORMAT(Datevalue(Texte[Texte]),"dd mmmm")
		lineageTag: fe72b221-b72b-40b7-9ed4-f06256a8e4f5
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Groupe
		dataType: string
		lineageTag: d6169009-6554-4cb6-8e6c-214e99ada84d
		summarizeBy: none
		sourceColumn: Groupe

		annotation SummarizationSetBy = Automatic

	column Catégorie
		dataType: string
		lineageTag: 6d7ebf1d-c147-4824-8297-cd54030f9cf7
		summarizeBy: none
		sourceColumn: Catégorie

		annotation SummarizationSetBy = Automatic

	column Texte
		dataType: string
		lineageTag: 71d425c4-2b23-4279-828e-f24ed09c4d77
		summarizeBy: none
		sourceColumn: Texte
		sortByColumn: Ordre

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Ordre
		dataType: int64
		formatString: 0
		lineageTag: f129ae1e-5195-4485-a3b4-2fb98478b0ef
		summarizeBy: sum
		sourceColumn: Ordre

		annotation SummarizationSetBy = Automatic

	column OrderAsDate = DATE(YEAR(TODAY()),MONTH(TODAY()),MAX(1,Texte[Ordre]))
		formatString: General Date
		lineageTag: 805e2d79-24c7-435d-b4e4-7f95eaa470f8
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 377e22a6-5c0f-4f10-8c8d-61cf4178b3c2
			defaultHierarchy: LocalDateTable_9db5f2ce-a674-4e44-b953-7fb5804f6e6e.'Hiérarchie de dates'

		annotation SummarizationSetBy = Automatic

	column Titre_ = Texte[Ordre] & " - " & Texte[Titre]
		lineageTag: 221f9910-ff9f-4f38-a107-e6b8f466bc3d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition Texte = m
		mode: import
		source =
				let
				    Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1EguBfb3VzBaOqYtk6nFXaXIUn5XsR1CYBC3KNrR-1sw"),
				    Texte_Table = Source{[name="Texte",ItemKind="Table"]}[Data],
				    #"Type modifié" = Table.TransformColumnTypes(Texte_Table,{{"Column3", type text}}),
				    #"En-têtes promus" = Table.PromoteHeaders(#"Type modifié", [PromoteAllScalars=true]),
				    #"Type modifié1" = Table.TransformColumnTypes(#"En-têtes promus",{{"Date", type date}, {"Ordre", Int64.Type}}),
				    #"Autres colonnes supprimées" = Table.SelectColumns(#"Type modifié1",{"Groupe", "Catégorie", "Titre", "Texte", "Date", "Ordre"})
				in
				    #"Autres colonnes supprimées"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

