table TypeLieux
	lineageTag: 9faf797b-55c1-43f7-89fb-783f9094644a

	column Type
		dataType: string
		lineageTag: cda76e06-91b1-4854-b1df-a7b0beeed47a
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column Ordre
		dataType: int64
		formatString: 0
		lineageTag: c6d386b0-f86b-44b0-ac9f-5b9468f4699c
		summarizeBy: none
		sourceColumn: Ordre

		annotation SummarizationSetBy = Automatic

	partition TypeLieux = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WcivKzytR0lEyU4rViVYKzcssObxSoai0uDgVKGiKLFiaXZSYmZeZmpcHkjIBSznn5yYlgrQbgblOIG5RSmpuKthMQ7CgY2lJEUiHsVJsLAA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Type = _t, Ordre = _t]),
				    #"Type modifié" = Table.TransformColumnTypes(Source,{{"Type", type text}, {"Ordre", Int64.Type}})
				in
				    #"Type modifié"

	annotation PBI_ResultType = Table

