table Texte_Hebdo
	lineageTag: 07b59ffb-39cd-4386-b7ab-1bdee64723f4

	measure Date-titre =
			
			VAR __date = CALCULATE(MAX(Texte_Hebdo[Texte]),Texte_Hebdo[Titre]="Date")
			VAR __date_format_date = max(Texte_Hebdo[Date])
			VAr __decompte=DATEDIFF(DATE(2022,2,24),__date_format_date,DAY)+1
			RETURN COMBINEVALUES(" ",__date, "- jour", __decompte)
		lineageTag: 1185f4a3-2e55-4fa2-8163-9a52f0f3f651

	column Texte
		dataType: string
		lineageTag: eaaa6058-1f9a-43b7-8826-299137c6d493
		summarizeBy: none
		sourceColumn: Texte
		sortByColumn: Prio

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Titre
		dataType: string
		lineageTag: cd088b89-a463-49f1-8e3b-2b57c99372be
		summarizeBy: none
		sourceColumn: Titre

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Catégorie
		dataType: string
		lineageTag: 650de36e-902c-4dd4-a4ed-324a37c4341c
		summarizeBy: none
		sourceColumn: Catégorie

		annotation SummarizationSetBy = Automatic

	column Titre_dyn = if(Texte_Hebdo[Catégorie]=Texte_Hebdo[Titre],BLANK(),Texte_Hebdo[Titre])
		lineageTag: 11f0fe19-54d7-44a5-932d-8075e77ac404
		summarizeBy: none
		sortByColumn: Prio

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: d mmmm
		lineageTag: 752993e5-1df5-4f77-a175-19bb5883251e
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Titre_display = CONCATENATE("➤ ", Texte_Hebdo[Titre])
		lineageTag: c0063245-dda1-4158-8fc4-3c0c77e20ba7
		summarizeBy: none

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Texte display' = COMBINEVALUES(" : ",Texte_Hebdo[Titre_display],Texte_Hebdo[Texte])
		lineageTag: fb288aae-a937-4223-8d59-a2b7b2deb233
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Résumé
		dataType: string
		lineageTag: a9de26bb-6964-42fd-80d4-79254825be19
		summarizeBy: none
		sourceColumn: Résumé

		annotation SummarizationSetBy = Automatic

	column Prio
		dataType: int64
		formatString: 0
		lineageTag: ffe52fc3-504a-46cb-a7c7-06817e8ec65e
		summarizeBy: sum
		sourceColumn: Prio

		annotation SummarizationSetBy = Automatic

	partition Texte_Hebdo = m
		mode: import
		source =
				let
				    Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1EguBfb3VzBaOqYtk6nFXaXIUn5XsR1CYBC3KNrR-1sw"),
				    Hebdo_Table = Source{[name="Hebdo",ItemKind="Table"]}[Data],
				    #"En-têtes promus" = Table.PromoteHeaders(Hebdo_Table, [PromoteAllScalars=true]),
				    #"Type modifié" = Table.TransformColumnTypes(#"En-têtes promus",{{"Date", type date}, {"Catégorie", type text}, {"Titre", type text}, {"Résumé", type text}, {"Texte", type text}, {"Prio", Int64.Type}}),
				    #"Lignes filtrées" = Table.SelectRows(#"Type modifié", each ([Titre] <> ""))
				in
				    #"Lignes filtrées"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

