table 'Assauts russes'
	lineageTag: 14dd23cd-4bb0-48a5-bbf9-52f7fc0e33fe

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9547f2e2-eab5-4a08-a2b7-31ea48b722fc
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Assauts russes'
		dataType: int64
		formatString: 0
		lineageTag: 896bc505-c1e1-4470-907d-0e5712036ad5
		summarizeBy: sum
		sourceColumn: Assauts russes

		annotation SummarizationSetBy = Automatic

	partition 'Assauts russes' = m
		mode: import
		source =
				let
				    Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1EguBfb3VzBaOqYtk6nFXaXIUn5XsR1CYBC3KNrR-1sw"),
				    #"nb assauts russes_Table" = Source{[name="nb assauts russes",ItemKind="Table"]}[Data],
				    #"En-têtes promus" = Table.PromoteHeaders(#"nb assauts russes_Table", [PromoteAllScalars=true]),
				    #"Type modifié" = Table.TransformColumnTypes(#"En-têtes promus",{{"Date", type date}, {"Assauts russes", Int64.Type}}),
				    #"Lignes filtrées" = Table.SelectRows(#"Type modifié", each ([Date] <> null))
				in
				    #"Lignes filtrées"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

